// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: comments.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO post_comments (id, created_at, comment_text, user_id, post_id)
VALUES (
        DEFAULT,
        NOW(),
        $1,
        $2,
        $3
    )
RETURNING id, created_at, comment_text, user_id, post_id
`

type CreateCommentParams struct {
	CommentText string
	UserID      uuid.UUID
	PostID      int32
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (PostComment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.CommentText, arg.UserID, arg.PostID)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CommentText,
		&i.UserID,
		&i.PostID,
	)
	return i, err
}

const getPostComments = `-- name: GetPostComments :many
SELECT id, created_at, comment_text, user_id, post_id FROM post_comments
WHERE post_id = $1
ORDER BY created_at DESC
OFFSET $2
LIMIT $3
`

type GetPostCommentsParams struct {
	PostID int32
	Offset int32
	Limit  int32
}

func (q *Queries) GetPostComments(ctx context.Context, arg GetPostCommentsParams) ([]PostComment, error) {
	rows, err := q.db.QueryContext(ctx, getPostComments, arg.PostID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostComment
	for rows.Next() {
		var i PostComment
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CommentText,
			&i.UserID,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
