// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Content   sql.NullString
	UserID    uuid.UUID
}

type PostComment struct {
	ID        uuid.UUID
	CreatedAt time.Time
	PostText  string
	UserID    uuid.UUID
	PostID    int32
}

type PostTag struct {
	ID     int32
	Tag    string
	PostID int32
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Email     string
	PwdHash   []byte
}
